// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>Validation.SchematronOutput</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Validation.SchematronOutput
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://purl.oclc.org/dsdl/svrl")]
    [System.Xml.Serialization.XmlRootAttribute("schematron-output", Namespace = "http://purl.oclc.org/dsdl/svrl", IsNullable = false)]
    public partial class schematronoutput
    {

        private schematronoutputNsprefixinattributevalues[] nsprefixinattributevaluesField;

        private schematronoutputActivepattern[] activepatternField;

        private string titleField;

        private string schemaVersionField;

        [System.Xml.Serialization.XmlElementAttribute("ns-prefix-in-attribute-values", Order = 0)]
        public schematronoutputNsprefixinattributevalues[] nsprefixinattributevalues
        {
            get
            {
                return this.nsprefixinattributevaluesField;
            }
            set
            {
                this.nsprefixinattributevaluesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("active-pattern", Order = 1)]
        public schematronoutputActivepattern[] activepattern
        {
            get
            {
                return this.activepatternField;
            }
            set
            {
                this.activepatternField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://purl.oclc.org/dsdl/svrl")]
    public partial class schematronoutputNsprefixinattributevalues
    {

        private string uriField;

        private string prefixField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://purl.oclc.org/dsdl/svrl")]
    public partial class schematronoutputActivepattern
    {

        private schematronoutputActivepatternFiredrule[] firedruleField;

        private string documentField;

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute("fired-rule", Order = 0)]
        public schematronoutputActivepatternFiredrule[] firedrule
        {
            get
            {
                return this.firedruleField;
            }
            set
            {
                this.firedruleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://purl.oclc.org/dsdl/svrl")]
    public partial class schematronoutputActivepatternFiredrule
    {

        private schematronoutputActivepatternFiredruleFailedassert[] failedassertField;

        private string contextField;

        [System.Xml.Serialization.XmlElementAttribute("failed-assert", Order = 0)]
        public schematronoutputActivepatternFiredruleFailedassert[] failedassert
        {
            get
            {
                return this.failedassertField;
            }
            set
            {
                this.failedassertField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://purl.oclc.org/dsdl/svrl")]
    public partial class schematronoutputActivepatternFiredruleFailedassert
    {

        private string textField;

        private string testField;

        private string locationField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }
}
